[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
    "npm run build"
]
